<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script type="text/javascript" src="{$basePath}/scripts/jquery.min.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/jquery.ajaxForm.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/jquery.nette.dependentselectbox.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/jquery.nette.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="{$basePath}/css/modal.css" type="text/css">
    <link type="text/css" href="{$basePath}/css/redmond/jquery-ui-1.8.5.custom.css" rel="stylesheet" />
    <script type="text/javascript" src="{$basePath}/scripts/addEvent.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/timepicker-cs.js"></script>
    <script type="text/javascript" src="{$basePath}/scripts/jquery.ui.datepicker-cs.js"></script>
</head>
<body>
{snippet:eventForm}
    {widget eventForm}
{/snippet}
</body>
</html>